### ISSUE TITLE
Add support for Text Objects

### ISSUE THREAD

**Issue by skube** [Wojnach/vimflowy#10]
Great extension! It would be fantastic to also have support for Text Objects like inner/all e.g. `ciw` or `daw` or `3daw`

**Comment by Wojnach** [comment]
yeah that would be nice! Some of them seem trivial to implement. I'll see if I can figure something out in the coming weeks, when I have time :) Feel free to make a pull request if you happen to solve it yourself before then!

**Comment by Wojnach** [comment]
To make this work we'll have to add 2 new states; 'Change' and 'Delete'. So far I've avoided creating states when possible, but I guess it is time for a bigger refactor :) This will take longer then expected to implement, but it is on its way.

**Comment by Wojnach** [comment]
Implemented 'ciw' and 'diw' in 1d0f98e0bc3e2b080595ac70e35b8a9fa37a3325

numeric prefixes 0-9 works as well. Blending numerics with the command doesn't work yet though. 'c4iw' for example doesn't work, but 4ciw does. 

I just noticed that you mentioned 'daw' and not 'diw' ... should be similar in their implementation. I'll write it up and add it next time.

**Comment by Wojnach** [comment]
implemented 'daw' binding in 56b3bbdc172493812a2e06d480e96ed720187dc7

The current implementation is a bit naive maybe. It's basically 'diw' + trim() of white space at the end. 

Let me know if we need a more proper implementation. For now it's good enough for my needs.
