### ISSUE TITLE
j/k keyboard navigation broken on new backlinks section

### ISSUE THREAD

**Issue by MattHulse** [Wojnach/vimflowy#12]
Using j/k navigation breaks on Backlinks.  When going down, the cursor skips the backlinks section entirely.  When going up, the cursor stops on the backlink section and won't go any further up.  Using the arrow keys is a workaround, but j/k navigation as it is doesn't work with backlinks.

Note: Backlinks is a labs feature.

**Comment by MattHulse** [comment]
Okay, I just created a simple repro for this and I couldn't get it to break with a newly created backlinks section.  There may be something else at play.  Maybe it has to do with older versions of the Backlinks since they are still a bit of a moving target.

**Comment by MattHulse** [comment]
This only happens if the bullet containing the Backlinks section _also_ has children.

It seems there's an extra svg viewbox tag in that case, maybe that's where it gets hung up.  This screenshot shows two bullets, each with backlinks.  The first one works fine (no child), the second one is broken (one child)

![image](https://user-images.githubusercontent.com/56975/109405218-65003880-792b-11eb-9021-226cd3e358fa.png)

**Comment by MattHulse** [comment]
The cursor up breaks in cursorMovent.js
https://github.com/Wojnach/vimflowy/blob/786ce764b25190c78999c8ee5df7bb3eda499451/cursorMovement.js#L181
because the cursorTarget is an SVGAnimatedString and it's className property does not have an 'includes' method.

See the following from console log:
```
Uncaught TypeError: cursorTarget.className.includes is not a function
    at moveCursorUp (VM30 cursorMovement.js:181)
    at Object.k (keybindings.js:18)
    at HTMLDivElement.<anonymous> (vimflowy.js:77)
    at HTMLDivElement.r (document_view.min.js?v=6aa8fea:1)
moveCursorUp @ VM30 cursorMovement.js:181
k @ keybindings.js:18
(anonymous) @ vimflowy.js:77
r @ document_view.min.js?v=6aa8fea:1
document_view.min.js?v=6aa8fea:1 [Violation] 'keydown' handler took 10161ms
```

**Comment by MattHulse** [comment]
No exceptions for cursor down.  I think it just finds that the next bullet doesn't have a project id and assumes there are no more siblings.  Not 100% sure.

**Comment by Wojnach** [comment]
Thanks for the bug report! :) 

It should be fixed in ff1ca6f

The chrome extension should be updated shortly as well

**Comment by MattHulse** [comment]
Thanks for the bug fix @Wojnach!  🎉 

Just tested it out and navigating up works great.  Navigating down still skips the entire backlink section (no errors, just bypasses it), but at least I can navigate back up to it if that is where I'm trying to get.

**Comment by Wojnach** [comment]
Yes, you are right! Navigating downwards from a backlink list to another backlink list will cause the cursor to skip that second backlink list and jump to the next item instead.

**Comment by Wojnach** [comment]
It should hopefully be fixed in 48bdc44

The chrome extension will be updated shortly as well.

**Comment by Wojnach** [comment]
let me know if you find more issues! :)

**Comment by MattHulse** [comment]
Works great!  Thanks!!!
