### ISSUE TITLE
Almost all functionality stopped working suddenly

### ISSUE THREAD

**Issue by aagerblad** [Wojnach/vimflowy#15]
I assume something has changed on the Workflowy side.
As of today I can't get any features to work. Updated to latest version (0.0.4.1) to make sure I wasn't missing some bugfix.
I can see the mode indicator in the bottom left corner, so the extension is running.
Examples of features not working:
Esc causes the search functionality to popup, rather than take me to NORMAL mode
Pressing any button in NORMAL mode will result in writing, rather than the intended command.

Is anyone else seeing this?

**Comment by aagerblad** [comment]
Nevermind, it was a user issue!

**Comment by richcorbs** [comment]
What was the user issue? This just happened to me.

**Comment by aagerblad** [comment]
I don't remember what the exact thing was, but I have removed 'jk' as a shortcut because it doesn't work if you write in swedish. I think there was some error in my code that made it fail. So if you haven't made changes yourself to the code I don't think it's the same thing
