### ISSUE TITLE
How to change the shortcut keys?

### ISSUE THREAD

**Issue by ydivho12123** [Wojnach/vimflowy#17]
Is there an entry for modifying shortcuts like vimium? Newbies feel completely unaware of where to modify

**Comment by Wojnach** [comment]
No sry. The keybindings are hardcoded. You'll have to download it, change the keys and then load it as a Developer Extension. 

1. Clone this repo (or your fork) somewhere on your filesystem.
2. edit keybinding.js or transparentKeybindings.js if you want to rebind or add new shortcuts.
3. go to **chrome**://extensions/ **(replace chrome with the browser you are using)**
4. click 'Load unpacked extension...' button right below 'Extensions' header in the top left corner of the page
5. point at the vimflowy repo directory
6. refresh workflowy page

Adding an options menu for rebinding keys is something I want as well but I don't have time to implement it atm.
