### ISSUE TITLE
[bug] Vimflowy not working as of today

### ISSUE THREAD

**Issue by romainchapou** [Wojnach/vimflowy#27]
Hi! First of all, thanks for the extension, I wouldn't be using workflowy without it.

As of today, vimflowy seems to not be working at all for me (and at least another user) as if the extension isn't loaded. It may be related to a recent workflowy update ?

In the console log of my browser, I can see an error: `Uncaught TypeError: Cannot read properties of null (reading 'addEventListener') at vimflowy.js:13:15`. I can see it's related to the creation of the `mainContainer` variable but I don't know much about web/js so I can't really help more than that.

**Comment by Wojnach** [comment]
Thanks for posting!

I submitted som changes to this repo that fixes the problem last week.

I haven’t had time to update the official extension. Will do that sometime next week.

//Sydney

On 5 Mar 2023, at 13:13, romainchapou ***@***.***> wrote:

﻿

Hi! First of all, thanks for the extension, I wouldn't be using workflowy without it.

As of today, vimflowy seems to not be working at all for me (and at least another user) as if the extension isn't loaded. It may be related to a recent workflowy update ?

In the console log of my browser, I can see an error: Uncaught TypeError: Cannot read properties of null (reading 'addEventListener') at vimflowy.js:13:15. I can see it's related to the creation of the mainContainer variable but I don't know much about web/js so I can't really help more than that.

**Comment by awillats** [comment]
fingers crossed the changes you already have planned will take care of it, but just adding some extra info, in case it helps later.

I also got:
`Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
    at vimflowy.js:13:15`
as well as a banner message:
`you are using an unsupported command-line flag --extensions-on-chrome-urls`
after updating to the latest version of Chrome.

**Comment by awillats** [comment]
@romainchapou and anyone else who's eager to have vimflowy functionality back ASAP, Wojnach's instructions here:
[README/#installation](https://github.com/Wojnach/vimflowy#installation)
worked for me, and the local version from the repo works! ( I just disabled the Chrome webstore version first )

**Comment by jorundoa** [comment]
Are there any plans of updating the chrome extension? It's kind of tiresome that i have to download it maually on all my computers

**Comment by Wojnach** [comment]
the new version should be live on the chrome extension store now. 

https://chrome.google.com/webstore/detail/vimflowy/jhoonlfajlaihdlcocigbpeacapaepng
