### ISSUE TITLE
Options page to control <jk> mapping

### ISSUE THREAD

**Issue by jvaelen** [Wojnach/vimflowy#28]
As someone who regularly types `jk` in insert mode, it's an inconvenience that it unintentionally brings me to normal mode.

I'd be willing to send a pull request to control (i.e. disable) this mapping. 

1. Are you open to this suggestion?
2. Do you have any requirements for the design of the options page and what else should go there?

I've attached a simple mock for what the options page could look like.

<img width="1920" alt="Screenshot 2023-03-09 at 23 50 38" src="https://user-images.githubusercontent.com/1927048/224178245-189ad0b3-49ee-42c4-9fdc-4c842a1962b0.png">

**Comment by Wojnach** [comment]
Nice! Yeah that would be great :) Thanks! 

I wanted to do a Options page in the past, but didn't have the time to finish it unfortunately. The idea was to have all the bindings rebindable via the options menu basically, but there are a bunch of stuff you can add there to make the extension more configurable. 

You can design and implement the options page however you want. Once you got it up and running I imagine you only have to read the bool value from the options menu, in the JK binding, and simply early out if the bool is true.

Some easy stuff that could be added to the options menu afterwards would some of the constant values that are defined in some of the files. For example settings for the color highlightning Alt-1 - Alt-9. The ctrl-J binding; which characters it shows on the bullets (might want to change that if you have non-english keyboard perhaps), etc. 

If you run into trouble getting it to work then you can always fork the master branch and remove the jk binding. 

good luck!

**Comment by jvaelen** [comment]
I took a look today and it's going to be a bit more work than I expected. I'm leaving on holiday and will take a stab once I get back. I'll share what I've learned.

The extension dynamically loads different scripts into the page from the content script (`contentscript_start.js` and `contentscript_idle.js`). The page context doesn't have access to the `chrome.storage` API where options are stored. A solution could be to bundle all scripts and run the bundle as content script so all code runs in the content context which has access to `chrome.storage`. That's the approach I'd probably take. 

Let me know if that makes sense or if you have any other ideas.

**Comment by Wojnach** [comment]
yeah sounds good, try it out :) 

The content scripts were split up because they had to be loaded in two different passes for them to work with workflowy website. But that was a few years ago, and since then the code has changed quite a lot - so maybe its not needed to split them up anymore.

**Comment by jvaelen** [comment]
I've created a PR: https://github.com/Wojnach/vimflowy/pull/31
