### ISSUE TITLE
Extension no longer loads

### ISSUE THREAD

**Issue by 8utl3r** [Wojnach/vimflowy#3]
Not sure if this is my fault or not but the extension is not loading on workflowy.com at the moment.

Steps taken to troubleshoot:
1. Reloaded page
2. Uninstalled and reinstalled extension
3. Restarted computer (macos, mojave)
4. Uninstalled and reinstalled extension

No dice on any of this. Haven't tried with a different computer yet. Other extensions are functional, even ones that read page content. Vimflowy extension has permission to read workflowy.com.

Thanks! I'll keep researching on my side as I'm able. Don't know if this is affecting anyone else (I kinda doubt it is).

**Comment by Wojnach** [comment]
It should work. The extension hasn't been updated since release and it is working for me. 

- It won't work in incognito mode by default. You have to enable that yourself. 
- It won't work on beta.workflowy.com or dev.workflowy.com - only on workflowy.com atm

**Comment by Wojnach** [comment]
It should be loaded if you see the mode indicator in bottom left hand corner of the browser. 

You can press F12, which will bring up the chrome dev menu and console,  and see if there are any red errors in the log.

**Comment by Wojnach** [comment]
And make sure you don't have 2 vimflowies enabled at once; i.e the official one from the chrome store and the one available here on github.

**Comment by 8utl3r** [comment]
It's fixed!

Weird presentation of error in webapp form on MacOS. I have workflowy saved as a webapp. When I opened workflowy in browser it worked fine and loaded the modal indicator. When in webapp it would not load. Leaving solution below for others who may encounter the same thing.

Solution: 'uninstall' webapp and create a new one. The extension loads fine now.
