### ISSUE TITLE
Support for "beta.workflowy.com"

### ISSUE THREAD

**Issue by 8utl3r** [Wojnach/vimflowy#7]
I'd like it to work for the beta too :)

**Comment by Wojnach** [comment]
should be an easy fix. I'll take a look at it in the coming weeks when I have time!

**Comment by MattHulse** [comment]
FYI: This is no longer needed since beta.workflowy.com is no longer used.  Experimental settings are turned on in the app and the URL is always workflowy.com.

**Comment by MattHulse** [comment]
My bad.  It turns out beta.workflowy.com is still used as a staging area.  This would still be a useful to have.
